language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov-config=.coveragerc --cov-report xml --cov=sa_gwdata
after_success:
  - python-codacy-coverage -r coverage.xml